<a href="https://colab.research.google.com/github/ThangallapallyHasini/2273-Natural-Language/blob/main/2273_b10_nlp_a6_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
d=pd.read_excel('/content/LDA-Data.xlsx')
print(d)

                             News
0   Virat scored century in match
1            BJP won in elections
2  Bumra took 5 wicket in a match
3  Congress form state government

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
lemmatizer = WordNetLemmatizer()
stopwords_set = set(stopwords.words('english'))

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers (keeping only alphabets)
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    # Tokenize the text
    words = nltk.word_tokenize(text)
    # Remove stopwords and perform lemmatization
    processed_words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords_set]
    # Rejoin words into a string
    return ' '.join(processed_words)

# Apply the preprocessing function to the 'News' column
d['Processed_News'] = d['News'].apply(preprocess_text)

# Display the original and processed news
print("Original News:")
print(d['News'])
print("\nProcessed News:")
print(d['Processed_News'])

Original News:
0     Virat scored century in match
1              BJP won in elections
2    Bumra took 5 wicket in a match
3    Congress form state government
Name: News, dtype: object

Processed News:
0        virat scored century match
1                      bjp election
2           bumra took wicket match
3    congress form state government
Name: Processed_News, dtype: object

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Re-create CountVectorizer and bow_matrix to ensure availability
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Number of topics to extract
num_topics = 2

# Initialize LDA model
lda_model = LatentDirichletAllocation(n_components=num_topics, random_state=42)

# Fit LDA model to the Bag of Words matrix
lda_model.fit(bow_matrix)

# Display the topics and their top keywords
print("Topics and their top keywords:")
def display_topics(model, feature_names, num_top_words):
    for topic_idx, topic in enumerate(model.components_): # Corrected from components__ to components_
        print(f"Topic {topic_idx + 1}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-num_top_words - 1:-1]]))

display_topics(lda_model, vectorizer.get_feature_names_out(), 5)

Topics and their top keywords:
Topic 1:
form government congress state election
Topic 2:
match virat century scored took

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Assuming 'd' DataFrame with 'Processed_News' column is already available

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'Processed_News' column
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Convert the BoW matrix to a DataFrame for better readability
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("Bag of Words Matrix (DataFrame):")
display(bow_df)

Bag of Words Matrix (DataFrame):

,bjp,bumra,century,congress,election,form,government,match,scored,state,took,virat,wicket
0,0,0,1,0,0,0,0,1,1,0,0,1,0
1,1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,1,0,0,1,0,1
3,0,0,0,1,0,1,1,0,0,1,0,0,0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'Processed_News' column
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Convert the BoW matrix to a DataFrame for better readability
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("Bag of Words Matrix:")
display(bow_df)

print("\nVocabulary (Feature Names):")
print(vectorizer.get_feature_names_out())

Bag of Words Matrix:

,bjp,bumra,century,congress,election,form,government,match,scored,state,took,virat,wicket
0,0,0,1,0,0,0,0,1,1,0,0,1,0
1,1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,1,0,0,1,0,1
3,0,0,0,1,0,1,1,0,0,1,0,0,0

Vocabulary (Feature Names):
['bjp' 'bumra' 'century' 'congress' 'election' 'form' 'government' 'match'
 'scored' 'state' 'took' 'virat' 'wicket']

In [ ]:
import pandas as pd
d=pd.read_csv('/content/arxiv_data.csv')
print(d)

                                                 titles  \
0     Survey on Semantic Stereo Matching / Semantic ...
1     FUTURE-AI: Guiding Principles and Consensus Re...
2     Enforcing Mutual Consistency of Hard Regions f...
3     Parameter Decoupling Strategy for Semi-supervi...
4     Background-Foreground Segmentation for Interio...
...                                                 ...
2379  Self-Supervised Visual Representation Learning...
2380  Graph-Based Neural Network Models with Multipl...
2381      Hard Negative Mixing for Contrastive Learning
2382  The LoCA Regret: A Consistent Metric to Evalua...
2383                                          Neural Co

                                              summaries  \
0     Stereo matching is one of the widely used tech...
1     The recent advancements in artificial intellig...
2     In this paper, we proposed a novel mutual cons...
3     Consistency training has proven to be an advan...
4     To ensure safety in automated driving, the cor...
...                                                 ...
2379  We create a framework for bootstrapping visual...
2380  Self-supervised learning is currently gaining ...
2381  Contrastive learning has become a key componen...
2382  Deep model-based Reinforcement Learning (RL) h...
2383                                                NaN

                              terms
0                ['cs.CV', 'cs.LG']
1       ['cs.CV', 'cs.AI', 'cs.LG']
2                ['cs.CV', 'cs.AI']
3                         ['cs.CV']
4                ['cs.CV', 'cs.LG']
...                             ...
2379                      ['cs.CV']
2380                      ['cs.LG']
2381             ['cs.CV', 'cs.LG']
2382  ['cs.LG', 'cs.AI', 'stat.ML']
2383                            NaN

[2384 rows x 3 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
lemmatizer = WordNetLemmatizer()
stopwords_set = set(stopwords.words('english'))

def preprocess_text(text):
    # Ensure text is a string to prevent errors with NaN or other types
    if pd.isna(text):
        return ""
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers (keeping only alphabets)
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    # Tokenize the text
    words = nltk.word_tokenize(text)
    # Remove stopwords and perform lemmatization
    processed_words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords_set]
    # Rejoin words into a string
    return ' '.join(processed_words)

# Apply the preprocessing function to the 'titles' column (assuming 'titles' is the intended column)
d['Processed_News'] = d['titles'].apply(preprocess_text)

# Display the original and processed news
print("Original Titles:")
print(d['titles'].head())
print("\nProcessed Titles (now in 'Processed_News' column):")
print(d['Processed_News'].head())

Original Titles:
0    Survey on Semantic Stereo Matching / Semantic ...
1    FUTURE-AI: Guiding Principles and Consensus Re...
2    Enforcing Mutual Consistency of Hard Regions f...
3    Parameter Decoupling Strategy for Semi-supervi...
4    Background-Foreground Segmentation for Interio...
Name: titles, dtype: object

Processed Titles (now in 'Processed_News' column):
0    survey semantic stereo matching semantic depth...
1    future ai guiding principle consensus recommen...
2    enforcing mutual consistency hard region semi ...
3    parameter decoupling strategy semi supervised ...
4    background foreground segmentation interior se...
Name: Processed_News, dtype: object

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Re-create CountVectorizer and bow_matrix to ensure availability
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Number of topics to extract
num_topics = 2

# Initialize LDA model
lda_model = LatentDirichletAllocation(n_components=num_topics, random_state=42)

# Fit LDA model to the Bag of Words matrix
lda_model.fit(bow_matrix)

# Display the topics and their top keywords
print("Topics and their top keywords:")
def display_topics(model, feature_names, num_top_words):
    for topic_idx, topic in enumerate(model.components_): # Corrected from components__ to components_
        print(f"Topic {topic_idx + 1}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-num_top_words - 1:-1]]))

display_topics(lda_model, vectorizer.get_feature_names_out(), 5)

Topics and their top keywords:
Topic 1:
learning representation supervised graph self
Topic 2:
segmentation image network deep based

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Assuming 'd' DataFrame with 'Processed_News' column is already available

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'Processed_News' column
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Convert the BoW matrix to a DataFrame for better readability
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("Bag of Words Matrix (DataFrame):")
display(bow_df)

Bag of Words Matrix (DataFrame):

,aaseg,abc,abdominal,ability,abnormal,absolute,abstract,abstraction,acav,accelerated,...,wrong,xerte,xlvin,xnet,year,yet,youtube,zda,zebrafish,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2379,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'Processed_News' column
bow_matrix = vectorizer.fit_transform(d['Processed_News'])

# Convert the BoW matrix to a DataFrame for better readability
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("Bag of Words Matrix:")
display(bow_df)

print("\nVocabulary (Feature Names):")
print(vectorizer.get_feature_names_out())

Bag of Words Matrix:

,aaseg,abc,abdominal,ability,abnormal,absolute,abstract,abstraction,acav,accelerated,...,wrong,xerte,xlvin,xnet,year,yet,youtube,zda,zebrafish,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2379,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Vocabulary (Feature Names):
['aaseg' 'abc' 'abdominal' ... 'zda' 'zebrafish' 'zero']